Default:
  ShareNetworkFromPhone: True # This should be True if you want to test the MPTCP
  Protocol: "MPTCPv0"
  Mode: "s" # s: server c: client
  SAddr: "140.112.20.183"
  sPort: "26427"
  
MPTCPv0:
  Interface: ["usb0", "usb1"]
  SubFlowNum: 2
  Backup: []
  Scheduler: "default"
  Bitrate: 1024 # 0 stands for no limit
  PathManage: "fullmesh"